version: "2"
services:
  enter_data:
    build: ./enter_data
    links:
      - mysql_db
    ports:
      - "8001:5000"

  mysql_db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_db:/docker-entrypoint-initdb.d/:r

  mongo_db:
     image: mongo
     environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: project1
     command: mongod --auth
     ports:
      - 27017:27017
     volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
     networks:
      - project1

  analytics-service:
    build: python
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
      - mysql_db
    environment:
      MYSQL_HOST: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: project1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MONGO_HOST: mongo
      MONGO_PORT: 27017

networks:
  project1:
