version: "2"
services:
  enter_data:
    build: ./enter_data
    links:
      - mysql_db
    ports:
      - "8001:5000"

  mysql_db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_db:/docker-entrypoint-initdb.d/:r

  mongodb:
     image: mongo
     environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONOGO_INITDB_ROOT_PASSWORD=root

  analytics-service:
    build: ./enter_data
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - mysql_db
