version: "2"
services:
  enter_data:
    build: ./enter_data
    links:
      - mysql_db
    ports:
      - "8001:5000"
    environment:
      AUTH_SERVICE_HOST: nodelogin
    depends_on:
      - nodelogin
    networks:
      - project1

  mysql_db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_db:/docker-entrypoint-initdb.d/:ro
    networks:
      - project1

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    hostname: test_mongo_db
    command: mongod --auth
    environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: analytics
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - project1

  analytics-service:
    build: ./analytic
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
      - mysql_db
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: project1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MONGO_HOST: mongo_db
      MONGO_PORT: 27017
    networks:
      - project1

  nodelogin:
    build: ./nodelogin
    ports:
      - "3001:3001"
    networks:
      - project1

  view_data:
    build: ./view_data
    ports:
      - "8004:8004"
    environment:
      AUTH_SERVICE_HOST: nodelogin
    depends_on:
      - nodelogin
    networks:
      - project1
    
networks:
  project1:
