version: "2"
services:
  enter_data:
    build: ./enter_data
    links:
      - mysql_db
    ports:
      - "8001:5000"
    environment:
      AUTH_SERVICE_HOST: nodelogin
    depends_on:
      - nodelogin
    networks:
      - project1

  mysql_db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_db:/docker-entrypoint-initdb.d/:ro
    networks:
      - project1

  nodelogin:
    build: ./nodelogin
    ports:
      - "3000:3000"
    networks:
      - project1

  view_data:
    build: ./view_data
    ports:
      - "8004:8004"
    environment:
      AUTH_SERVICE_HOST: nodelogin
    depends_on:
      - nodelogin
    networks:
      - project1
    
networks:
  project1:
